version: '3.8'
services:
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development

  nextjs:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3721:3000"

